dist: trusty
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - cmake
notifications:
  email: false
  slack:
    rooms:
      secure: Ijtfw9g9bkzDykAeuQc4OffsIigmI1sG15eoiE97HlNYZW/q/RkOcyUPfpNvzgo8jby/IdvTjqtRf90IB63hG0nHUBEzxAxbiAi/r6b+KzSRpYNbkXZGlx2i8dHwibT2NVRuowMWRAa6nlh8EUQTCVBuIdQaI83ipmiAoGRFNr+SSO+snhGNfVZoOK2JGbvScgiaBWZRLE9TfjWli0vuuVSj6g4vVVl6TGjNHe5aplYFpeCZTAfiJO/gx9frNx8d3eMMdZ/7rYIHSCPnQhiY7bS24Q3/CKHGiu4ZBNHXYvXjUBlmVANzvgMcm826O85Aa2gTju5A+uK38DstLKWeBU/lk5ONbSKdlVrvjcKfzV2gkgobTeK46NmOZ5/GVFyRDRIUhdoKEEQSLJnuFG/IKh0OhVsoOJcCSZXKUakAw9tN2LiAttpLEe4gkW6YW+AJkbWYH1ZZvBA/DsFa5VWpjkEONfiGK+i1rXt6JXj/0YXlUb54Sb6de/eOwuCnlH/w5PU6pZRSI+w0MQkl57V0JDSZsWGEnxOeI0apwHZVWdZ0ThboRy7R/EoAhYHNhKwAEtYqXX8domL0cYDK7G1sFwDgF0yHDxp3FkN1I3/5QBtF6bds4kWGFbQEbN5pnYPRlxJ+aEDC0lgo9mXC30IR/PZqSQmAdmAk+maywGZyzWo=
    on_success: never
    on_failure: always
    on_pull_requests: false
before_script: mkdir build && cd build
script: cmake .. && cmake --build .